version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - app-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - app-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: url_shortener
    ports:
      - "5431:5432"
    networks:
      - app-net
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass","password" ]
    networks:
      - app-net
    healthcheck:
      test: redis-cli -a password ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: ./service_discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5



  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - HOSTNAME=api-gateway
      - PORT=8001
      - FRONTEND_HOST=http://localhost:3000
    networks:
      - app-net

  counter-service:
    container_name: counter_service

    build:
      context: ./counter
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - PORT=8085
    networks:
      - app-net

  shortener_service:
    build:
      context: ./shortner
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    depends_on:
      eureka-server:
        condition: service_started
      counter-service:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy


    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - PORT=9010
      - DB_URL=jdbc:postgresql://postgres:5432/url_shortener
      - KAFKA_SERVER_URL=kafka:9092
      - COUNTER_URL=http://counter-service:8085/get
      - API_GATEWAY_URL=http://api-gateway:8001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - HOSTNAME=shortener-service
      - PORT=9010
    networks:
      - app-net

  analytic_service:
    build:
      context: ./analytics_service
      dockerfile: Dockerfile
    ports:
      - "9009:9009"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - MONGO_URI=GET_YOUR_URL
      - KAFKA_SERVER_URL=kafka:9092
      - KAFKA_SERVER_STREAM_URL=kafka:9092
      - SERVICE_AUTH_TOKEN=Bearer SERVICE_AUTH
      - SERVICE_VERITFICATION_TOKEN=Bearer SERVICE_AUTH
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - HOSTNAME=analytics-service
      - PORT=9009
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

    networks:
      - app-net

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:postgresql://postgres:5432/url_shortener
      - HOSTNAME=user-service
    networks:
      - app-net



networks:
  app-net:
    driver: bridge