eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}  # URL of the Eureka Server
    registerWithEureka: true  # Register this service with Eureka
    fetchRegistry: true  # Fetch registry info from Eureka
  instance:
    prefer-ip-address: true
    instance-id: ${HOSTNAME:localhost}:${PORT:8001}
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


      routes:
        - id: shortner-redirect
          uri: lb://shortner
          filters:
            - RewritePath=/s/(?<segment>.*), /s/$\{segment}
          predicates:
            - Path=/s/**
        - id: url-api
          uri: lb://shortner
          filters:
            - AuthenticationFilter
            - ApiResponseTransformFilter
            - RewritePath=/api/v1/(?<segment>.*), /v1/$\{segment}
          predicates:
            - Path=/api/v1/url/**
        - id: shortener-api
          uri: lb://shortner
          filters:
            - AuthenticationFilter
            - ApiResponseTransformFilter
            - RewritePath=/api/v1/(?<segment>.*), /v1/$\{segment}
          predicates:
            - Path=/api/v1/shortener/** , /shortener-service/v3/api-docs

        - id: user-service
          uri: lb://user-service
          filters:
            - AuthenticationFilter
            - ApiResponseTransformFilter
            - RewritePath=/api/v1/user/(?<segment>.*), /v1/$\{segment}
          predicates:
            - Path=/api/v1/user/** , /user-service/v3/api-docs
        - id: analytics-service
          uri: lb://analytics-service
          filters:
            - AuthenticationFilter
            - ApiResponseTransformFilter
            - RewritePath=/api/v1/analytics/(?<segment>.*), /v1/$\{segment}
          predicates:
            - Path=/api/v1/analytics/** , /analytics-service/v3/api-docs

        - id: openapi
          uri: lb://api-gateway
          predicates:

            - Path=/*/v3/api-docs
          filters:
            # Rewrites /<service-name>/v3/api-docs to /v3/api-docs before forwarding
            - RewritePath=/(?<path>.*)/v3/api-docs, /v3/api-docs
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /analytics-service/v3/api-docs
        name: Analytics Service
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /shortener-service/v3/api-docs
        name: Shortener Service




application:
  properties:
    frontend_host: ${FRONTEND_HOST:http://localhost:3000}
server:
  port: 8001
